/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:e0132707-2a8a-4628-b9d1-b478298d400f",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_QHWQ4WoBI",
    "aws_user_pools_web_client_id": "3p0jarcrmmsh410au0i4k2ftpc",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://snuwpsrbqzditpcdyfrzibon7i.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-zm3eb2l3cbhixnhtqd33rjx75m",
    "aws_content_delivery_bucket": "servlist-20210421012340-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "https://djuy9lwxu9t3y.cloudfront.net"
};


export default awsmobile;
